/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_splash;

import ansh_gui.Disclaimer;
import ansh_gui.Login;



/**
 *
 * @author lab
 */
public class screen extends javax.swing.JFrame {

    /**
     * Creates new form screen
     */
    public screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hello test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(648, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String[] x = { "Main Menu","Project Manager", "Subject Manager", "User Control", "User Module","Master Entry","Data Module",
            "Project Tables","Subject Data","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Establishing SQL Connection","Authenticating SQL Server",
            "Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Project Modules","Cache Table Optimising Module","Cache Table Optimising Module","Cache Table Optimising Module"," Jmodules","Access Verifier",
        "Addition Module","Project Manager","Project Manager", "Subject Manager", "Subject Forms",  "User Control", "Subject Module","Master Entry","Data Module",
            "Project Tables","Project Tables","Subject Data","Establishing SQL Connection","Authenticating SQL Server","Authenticating SQL Server","Authenticating SQL Server","Project Modules","Cache Table Optimising Module","Cache Table Optimising Module","Cache Table Optimising Module"," Jmodules","ANSH"};
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        splash Splash = new splash();
        Splash.setVisible(true);
       Disclaimer frm=new Disclaimer();
//  frm.setVisible(true);
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(40);
                Splash.percent.setText(Integer.toString(i)+"%");
                Splash.progress.setValue(i);
                if(i<60)
                {  Splash.modules.setText(x[i]+"...");}
                if(i==100)
                {
                     Splash.setVisible(false);
                       frm.setVisible(true);  
                }
            }
        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
