/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_view;
import ansh_gui.Connect;
import ansh_gui.query_result;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.io.IOException;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import net.proteanit.sql.DbUtils;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;



/**
 *
 * @author lab
 */
public class user_panel extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
static String upublic,npublic;
 String name,u_id,s_tmp;
 int sid;
    /**
     * Creates new form NewJFrame
     * @param uname
     */
    public user_panel(String uname) {
    try {
            con= Connect.ConnectDB();

        String sql = "select * from Users where u_id=? ";
         pst = con.prepareStatement(sql);
         u_id=uname;
         upublic=uname;
        pst.setString(1,uname );
        rs=pst.executeQuery();
        
        if(rs.next())
        {
            name=rs.getString(2);
            npublic=name;
        }

        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
          String sqlc = "SELECT * FROM `Master_record`";
         pst = con.prepareStatement(sqlc);
         u_id=uname;
        //pst.setString(1,uname );
        rs=pst.executeQuery();

        while(rs.next())
        {
            
            
            searchcombo.addItem(rs.getString(2));
            searchcombo.addItem(rs.getString(3));
            searchcombo.addItem(rs.getString(9));
            searchcombo1.addItem(rs.getString(2));
        
          
            
        }
        
        AutoCompleteDecorator.decorate(searchcombo);
           AutoCompleteDecorator.decorate(searchcombo1);
       String pro = getproname();
  //   System.out.println(pro);
      pname.setText(pro);    
        //setLocati/*onRelativeTo(null);*/
    } catch (SQLException ex) {
        Logger.getLogger(user_panel.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, ex);
    }
                

    }

    private String getproname()
    {
     
    String projname = null,proj;
    

                        try{
                  
        con= Connect.ConnectDB();
    String uid=user_view.user_panel.upublic;

        
              String sqlud="select *  from Users  WHERE u_id LIKE '" +uid+ "' ";
      
            //JOptionPane.showMessageDialog(null,sql);
          pst=con.prepareStatement(sqlud);
          rs= pst.executeQuery();
          if(rs.next())
          {
             

              proj=rs.getString("Proj");
                String sqlp="select Name  from Project WHERE Prj_ID LIKE '" +proj+ "' ";
      
            //JOptionPane.showMessageDialog(null,sql);
          pst=con.prepareStatement(sqlp);
          rs= pst.executeQuery();
      
              
          if(rs.next())
          {
              projname=rs.getString("Name");
            
          }
          else
              projname="Not alloted";
          }
         }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
    }
   
         return projname;
    }
//    private void displayname(String id)
//    {
//    try {
//        String sql = "select * from Users where u_id=? ";
//      PreparedStatement ps;
//        ps = con.prepareStatement(sql);
//        ps.setString(1,id );
//        ResultSet result=ps.executeQuery();
//        
//        if(result.next())
//        {
//             String name=rs.getString("Name");
//             userlabel.setText(name);
//        }
//    } catch (SQLException ex) {
//       // Logger.getLogger(user_panel.class.getName()).log(Level.SEVERE, null, ex);
//        JOptionPane.showMessageDialog(null, ex);
//    }
//            
//                
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        test = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchcombo = new javax.swing.JComboBox<String>();
        jPanel2 = new javax.swing.JPanel();
        searchcombo1 = new javax.swing.JComboBox<String>();
        jButton6 = new javax.swing.JButton();
        srpanel = new javax.swing.JPanel();
        addresslabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        namelabel1 = new javax.swing.JLabel();
        subjectlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User Panel | ANSH");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(705, 361));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setText("Welcome");

        userlabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        userlabel.setText(name);

        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Settings");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Subject Manager");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Master Sheet Log");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Image Viewer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        test.setText("Project Data");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_mgr/sr.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        searchcombo.setEditable(true);
        searchcombo.setMaximumRowCount(3);
        searchcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
        searchcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcomboActionPerformed(evt);
            }
        });
        searchcombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchcomboKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchcomboKeyPressed(evt);
            }
        });

        searchcombo1.setEditable(true);
        searchcombo1.setMaximumRowCount(3);
        searchcombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enter SubjectID" }));
        searchcombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchcombo1MouseClicked(evt);
            }
        });
        searchcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcombo1ActionPerformed(evt);
            }
        });
        searchcombo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchcombo1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchcombo1KeyPressed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_mgr/sr.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        addresslabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        addresslabel.setText("jLabel7");

        emaillabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        emaillabel.setText("jLabel7");

        phonelabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        phonelabel.setText("jLabel7");

        namelabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        namelabel.setText("jLabel6");
        namelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        namelabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        namelabel1.setText("jLabel6");
        namelabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        subjectlabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        subjectlabel.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setText("Subject ID");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setText("Address");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout srpanelLayout = new javax.swing.GroupLayout(srpanel);
        srpanel.setLayout(srpanelLayout);
        srpanelLayout.setHorizontalGroup(
            srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srpanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addGroup(srpanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addresslabel)
                    .addComponent(emaillabel)
                    .addComponent(phonelabel)
                    .addGroup(srpanelLayout.createSequentialGroup()
                        .addComponent(namelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namelabel1))
                    .addComponent(subjectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, srpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(31, 31, 31))
        );
        srpanelLayout.setVerticalGroup(
            srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, srpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subjectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namelabel)
                    .addComponent(namelabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phonelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emaillabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(srpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addresslabel))
                .addGap(57, 57, 57)
                .addComponent(jButton8)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(srpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(srpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Project:");

        pname.setText("jLabel3");

        jLabel3.setText("Master Search");

        jMenu1.setText("Subject");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Login");

        jMenuItem2.setText("Change Password");
        jMenu2.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Login Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data");

        jMenuItem4.setText("Project");
        jMenu3.add(jMenuItem4);

        jMenuItem3.setText("Subject");
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Image");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Project");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(searchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(searchcombo)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userlabel))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton7))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    try {
           String sql2 = "SELECT MAX(sessionid) FROM users_log WHERE u_id = ? ";
         pst = con.prepareStatement(sql2);
      
        pst.setString(1,u_id );
     // JOptionPane.showMessageDialog(null, u_id);
        rs=pst.executeQuery();
        
        if(rs.next())
        {
           // s_tmp=rs.getString(1);
            //sid=Integer.parseInt(s_tmp);
           sid=rs.getInt(1);
       //    JOptionPane.showMessageDialog(null, sid);
        }
//SELECT MAX(sessionid) FROM users_log WHERE u_id = 'admin'
        java.awt.Window win[] = java.awt.Window.getWindows();
        for(int i=0;i<win.length;i++){
            win[i].dispose();
        }
       Calendar calendar = Calendar.getInstance();
    java.sql.Timestamp ourJavaTimestampObject = new java.sql.Timestamp(calendar.getTime().getTime());
        String sql_up= "UPDATE  users_log  SET  logouttime  = ?  WHERE sessionid  = ?";
        pst=con.prepareStatement(sql_up);
         pst.setTimestamp(1, ourJavaTimestampObject);
         pst.setInt(2,sid );
        pst.execute();
 
        ansh_gui.Login frm=new ansh_gui.Login();
        frm.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(user_panel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

  
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 String ObjButtons[] = {"No","Yes"};
    int PromptResult = JOptionPane.showOptionDialog(null, 
        "Are you sure you want to exit?", "ANSH", 
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, 
        ObjButtons,ObjButtons[0]);
    if(PromptResult==1)
    {
                con= Connect.ConnectDB();
           try {
                String sql2 = "SELECT MAX(sessionid) FROM users_log WHERE u_id = ? ";
         pst = con.prepareStatement(sql2);
      
        pst.setString(1,u_id );
      //JOptionPane.showMessageDialog(null, u_id);
        rs=pst.executeQuery();
        
        if(rs.next())
        {
           // s_tmp=rs.getString(1);
            //sid=Integer.parseInt(s_tmp);
           sid=rs.getInt(1);
        //   JOptionPane.showMessageDialog(null, sid);
        }
//SELECT MAX(sessionid) FROM users_log WHERE u_id = 'admin'
             java.awt.Window win[] = java.awt.Window.getWindows();
               for(int i=0;i<win.length;i++){
                   win[i].dispose();
               }
               Calendar calendar = Calendar.getInstance();
               java.sql.Timestamp ourJavaTimestampObject = new java.sql.Timestamp(calendar.getTime().getTime());
               String sql_up= "UPDATE  users_log  SET  logouttime  = ?  WHERE sessionid  = ?";
               pst=con.prepareStatement(sql_up);
               pst.setTimestamp(1, ourJavaTimestampObject);
               //   JOptionPane.showMessageDialog(null, sid);
               pst.setInt(2,sid );
               pst.execute();
               System.exit(0);
               
           } catch (SQLException ex) {
               Logger.getLogger(user_panel.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    }//GEN-LAST:event_formWindowClosing
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      user_view.user_subject.Subject_form frm = new user_view.user_subject.Subject_form();
      frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search()
    {
        String key = (String) searchcombo.getSelectedItem();
       // JOptionPane.showMessageDialog(null, key);
        search_result frm = new search_result(key);
               
        frm.setVisible(true);
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        search();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void labelassign()
    {
         String key = "%"+ searchcombo1.getSelectedItem()+"%";
    try {
          con= Connect.ConnectDB();
        String sqlc = "SELECT * FROM `Personal_data` WHERE `SubjectId`LIKE '"+key+"' OR `First_name` LIKE '"+key+"'";
        pst = con.prepareStatement(sqlc);
        
        rs=pst.executeQuery();
        if(rs.next())
        {
            subjectlabel.setText(rs.getString(1));
            namelabel.setText(rs.getString(2));
             namelabel1.setText(rs.getString(3));
             phonelabel.setText(rs.getString(7));
             emaillabel.setText(rs.getString(8));
             addresslabel.setText(rs.getString(9));
        }
    } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, ex, "ANSH", ERROR);
    }
  
    }
    private void searchcomboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchcomboKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           search();
       }
    }//GEN-LAST:event_searchcomboKeyPressed

    private void searchcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcomboActionPerformed
 
    }//GEN-LAST:event_searchcomboActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     login_det frm = new login_det();
     frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  settings set = new settings();
  set.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchcomboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchcomboKeyTyped
      if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           search();
       }
    }//GEN-LAST:event_searchcomboKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     scan_log frm = new scan_log();
     frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        String URL = "http://172.31.15.127/build/";
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
    } catch (IOException ex) {
        Logger.getLogger(user_panel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
project_browse fun = new project_browse(getproname());
fun.setVisible(true);
    }//GEN-LAST:event_testActionPerformed

    private void searchcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchcombo1ActionPerformed

    private void searchcombo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchcombo1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchcombo1KeyTyped

    private void searchcombo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchcombo1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchcombo1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     labelassign();
        searchcombo1.hide();
    jButton6.hide();
    srpanel.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    searchcombo1.setVisible(true);
   jButton6.setVisible(true);
   srpanel.hide();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void searchcombo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcombo1MouseClicked
        searchcombo1.setModel(null);
    }//GEN-LAST:event_searchcombo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
           java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namelabel1;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel pname;
    private javax.swing.JComboBox<String> searchcombo;
    private javax.swing.JComboBox<String> searchcombo1;
    private javax.swing.JPanel srpanel;
    private javax.swing.JLabel subjectlabel;
    private javax.swing.JButton test;
    public javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
